### ISSUE TITLE
Clr and CoreClr functional tests failing

### ISSUE THREAD

**Issue by jbagga** [aspnet/IISIntegration#343]
The following functional tests are failing on the CI (primarily on Win7, 2008 and 2012)

- [`HelloWorldTests.HelloWorld_IISExpress(runtimeFlavor: Clr, architecture: x64, applicationBaseUrl`](https://github.com/aspnet/IISIntegration/blob/dev/test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HelloWorldTest.cs#L28)
[Failure details](http://aspnetci/project.html?projectId=XPlat&testNameId=-7048761748472214998&tab=testDetails)

- [`HelloWorldTests.HelloWorld_IISExpress(runtimeFlavor: CoreClr, architecture: x64, applicationBaseUrl]`](https://github.com/aspnet/IISIntegration/blob/dev/test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HelloWorldTest.cs#L28)
[Failure details](http://aspnetci/project.html?projectId=XPlat&testNameId=5873434389658936030&tab=testDetails)

- [`NtlmAuthenticationTests.NtlmAuthentication(serverType: IISExpress, runtimeFlavor: Clr, architecture`](https://github.com/aspnet/IISIntegration/blob/dev/test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/NtlmAuthentationTest.cs#L36)
[Failure details](http://aspnetci/project.html?projectId=XPlat&testNameId=-5760046834214239752&tab=testDetails)

- [`HttpsTest.Https_HelloWorld_NoClientCert(runtimeFlavor: CoreClr, architecture: x64, applicationBaseUrl`](https://github.com/aspnet/IISIntegration/blob/dev/test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs#L90)
[Failure details](http://aspnetci/project.html?projectId=XPlat&testNameId=3370220398734179269&tab=testDetails)

- [`HttpsTest.Https_HelloWorld(runtimeFlavor: Clr, architecture: x64, applicationBaseUrl`](https://github.com/aspnet/IISIntegration/blob/dev/test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HttpsTest.cs#L27)
[Failure details](http://aspnetci/project.html?projectId=XPlat&testNameId=-7480640104508999104&tab=testDetails)

Exception message: http://aspnetci/viewLog.html?buildId=191645&buildTypeId=Lite_UniverseTest&tab=buildLog#_focus=96828

cc @Tratcher

**Comment by pranavkm** [comment]
Might have been addressed by https://github.com/aspnet/IISIntegration/commit/cdadfd48d0fc8b6d16a0067e5865a76f8ec05c75

**Comment by JunTaoLuo** [comment]
Yea looks like an actual issue with tests, not flakiness.

**Comment by jbagga** [comment]
Https_HelloWorld_NoClientCert(runtimeFlavor: CoreClr, architecture: x64, applicationBaseUrl is still failing on Win2012 Universe
http://aspnetci/viewLog.html?buildId=192569&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

@pranavkm @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Hmm that was passing until our noon build. Taking a look now.

**Comment by pranavkm** [comment]
Might be the change to Hosting that's tripping this.

**Comment by JunTaoLuo** [comment]
This was fixed in https://github.com/aspnet/IISIntegration/pull/345.
